version: '2.33.1'

services:
  db:
    image: postgres:16-alpine
    container_name: snake-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snake_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: snake-app
    build: .
    restart: on-failure
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/snake_db?sslmode=disable"
    depends_on:
      - db

volumes:
  postgres-data: